# Generated by Django 2.2.10 on 2020-03-20 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
